// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WattManager.Infrastructure.Persistence;

#nullable disable

namespace WattManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617114936_InitialWattManagerMigration")]
    partial class InitialWattManagerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WattManager.Domain.Entities.Centrale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapaciteMax")
                        .HasColumnType("double");

                    b.Property<int?>("IngenieurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeEnergie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IngenieurId");

                    b.ToTable("centrales", (string)null);
                });

            modelBuilder.Entity("WattManager.Domain.Entities.Ingenieur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ingenieurs", (string)null);
                });

            modelBuilder.Entity("WattManager.Domain.Entities.Centrale", b =>
                {
                    b.HasOne("WattManager.Domain.Entities.Ingenieur", "Ingenieur")
                        .WithMany("Centrales")
                        .HasForeignKey("IngenieurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingenieur");
                });

            modelBuilder.Entity("WattManager.Domain.Entities.Ingenieur", b =>
                {
                    b.Navigation("Centrales");
                });
#pragma warning restore 612, 618
        }
    }
}
